name: Build ImmortalWrt for Oray X1 Pro
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Build Environment
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_url: https://github.com/immortalwrt/immortalwrt.git
          openwrt_branch: master
          openwrt_commit: 88e20a065f860c00928282f38408232818281887
          openwrt_config_target: mediatek/filogic
          openwrt_custom_files: files
          openwrt_custom_config: .config
