name: Build ImmortalWrt for Oray X1 Pro
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build OpenWrt
        uses: make-openwrt/make-openwrt@main
        with:
          repo: immortalwrt/immortalwrt
          branch: master
          target: mediatek/filogic
          config: .config
          files: files
